/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Auth: typeof import('./components/Auth.vue')['default']
    BuildImage: typeof import('./components/BuildImage.vue')['default']
    Camera: typeof import('./components/Camera.vue')['default']
    Chart: typeof import('./components/Chart.vue')['default']
    ChatGpt: typeof import('./components/ChatGpt.vue')['default']
    CodeServer: typeof import('./components/CodeServer.vue')['default']
    Dark: typeof import('./components/Dark.vue')['default']
    DatabaseKey: typeof import('./components/DatabaseKey.vue')['default']
    DeployRepo: typeof import('./components/DeployRepo.vue')['default']
    DockerPull: typeof import('./components/DockerPull.vue')['default']
    Editor: typeof import('./components/Editor.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Message: typeof import('./components/Message.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    Notifier: typeof import('./components/Notifier.vue')['default']
    ProgressBar: typeof import('./components/ProgressBar.vue')['default']
    Request: typeof import('./components/Request.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareScreen: typeof import('./components/ShareScreen.vue')['default']
    SingleUpload: typeof import('./components/SingleUpload.vue')['default']
    Socket: typeof import('./components/Socket.vue')['default']
    Sse: typeof import('./components/Sse.vue')['default']
    Tree: typeof import('./components/Tree.vue')['default']
    TreeNode: typeof import('./components/TreeNode.vue')['default']
    Upload: typeof import('./components/Upload.vue')['default']
    User: typeof import('./components/User.vue')['default']
    Voice: typeof import('./components/Voice.vue')['default']
    Ws: typeof import('./components/Ws.vue')['default']
  }
}
